spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test?useSSL=true
      username: root
      password: feng
      driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
       cache: false
       mode: LEGACYHTML5
    cache:
      type: hazelcast
    hazelcast:
      config: hazelcast.xml
server:
  port: 8081