server:
  port: 8080

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test?useSSL=true
      username: root
      password: feng
      driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
       cache: false
       mode: LEGACYHTML5
    cache:
      type: hazelcast
    hazelcast:
      config: hazelcast.xml

    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 15000
      password: feng
      pool:
        max-active: 8
        min-idle: 2
        max-wait: 5000
